//alert("Hello");
var str = "Hello world";
var arr = ["asdf", "qwer", "vcxs"];
//console.log(str.length);
//console.log(str.charAt(0));
//console.log(str.indexOf("world"));
//console.log(str.substr(0,2));
//console.log(str.substring(0,2));
//console.log(str.slice(0,2));
//console.log(arr.pop(0));
window.document.body.getElementsByTagName("p")[0].innerHTML = str;
